const AMENITIES = [
  "24-hour check-in",
  "Accessible-height bed",
  "Accessible-height toilet",
  "Air conditioning",
  "BBQ grill",
  "Baby bath",
  "Babysitter recommendations",
  "Balcony",
  "Bath towel",
  "Bathroom essentials",
  "Bathtub",
  "Bathtub with bath chair",
  "Beach essentials",
  "Beach view",
  "Beachfront",
  "Bed linens",
  "Bedroom comforts",
  "Body soap",
  "Breakfast",
  "Breakfast table",
  "Building staff",
  "Buzzer/wireless intercom",
  "Cable TV",
  "Carbon monoxide detector",
  "Cat(s)",
  "Changing table",
  "Children’s books and toys",
  "Children’s dinnerware",
  "Cleaning before checkout",
  "Coffee maker",
  "Convection oven",
  "Cooking basics",
  "Crib",
  "DVD player",
  "Disabled parking spot",
  "Dishes and silverware",
  "Dishwasher",
  "Dog(s)",
  "Doorman",
  "Double oven",
  "Dryer",
  "Elevator",
  "En suite bathroom",
  "Espresso machine",
  "Essentials",
  "Ethernet connection",
  "Extra pillows and blankets",
  "Family/kid friendly",
  "Fire extinguisher",
  "Fireplace guards",
  "Firm mattress",
  "First aid kit",
  "Fixed grab bars for shower",
  "Fixed grab bars for toilet",
  "Flat path to front door",
  "Free parking on premises",
  "Free street parking",
  "Full kitchen",
  "Game console",
  "Garden or backyard",
  "Ground floor access",
  "Gym",
  "Hair dryer",
  "Handheld shower head",
  "Hangers",
  "Heated towel rack",
  "Heating",
  "High chair",
  "Host greets you",
  "Hot tub",
  "Hot water",
  "Hot water kettle",
  "Indoor fireplace",
  "Internet",
  "Iron",
  "Keypad",
  "Kitchen",
  "Kitchenette",
  "Laptop friendly workspace",
  "Lock on bedroom door",
  "Lockbox",
  "Long term stays allowed",
  "Luggage dropoff allowed",
  "Microwave",
  "Mountain view",
  "Murphy bed",
  "Other",
  "Other pet(s)",
  "Outlet covers",
  "Oven",
  "Pack ’n Play/travel crib",
  "Paid parking off premises",
  "Paid parking on premises",
  "Patio or balcony",
  "Pets allowed",
  "Pets live on this property",
  "Pocket wifi",
  "Pool",
  "Pool with pool hoist",
  "Private bathroom",
  "Private entrance",
  "Private living room",
  "Rain shower",
  "Refrigerator",
  "Roll-in shower",
  "Room-darkening shades",
  "Safety card",
  "Self check-in",
  "Shampoo",
  "Single level home",
  "Smart TV",
  "Smart lock",
  "Smoke detector",
  "Smoking allowed",
  "Sound system",
  "Stair gates",
  "Standing valet",
  "Step-free access",
  "Stove",
  "Suitable for events",
  "TV",
  "Terrace",
  "Toilet paper",
  "Walk-in shower",
  "Warming drawer",
  "Washer",
  "Waterfront",
  "Well-lit path to entrance",
  "Wheelchair accessible",
  "Wide clearance to bed",
  "Wide clearance to shower",
  "Wide doorway",
  "Wide entryway",
  "Wide hallway clearance",
  "Wifi",
  "Window guards",
  "toilet",
];
//todo: complete
export function Amenity({ amenityName }) {
  return <div className="amenity">{amenityName}</div>;
}
